### ISSUE TITLE
feat: simonamarcu2 - add skills category 

### ISSUE THREAD

**Issue by simonamarcu2** [codetapacademy/html-css-javascript-starter#132]
* [ ] feat: simonamarcu2 - add root list for skills #133
* [ ] feat: simonamarcu2 - header for skill list #134
* [ ] feat: simonamarcu2 - add ending content indicator #135
