### ISSUE TITLE
feat: simonamarcu2 - welcoming start

### ISSUE THREAD

**Issue by simonamarcu2** [codetapacademy/html-css-javascript-starter#83]
* [ ] feat: simonamarcu2 - titles and subtitles #87 
* [ ] feat: simonamarcu2 - insert title category and a shadowed box #124
* [ ] feat: simonamarcu2 - insert download button #127
* [ ] feat: simonamarcu2 - insert next button #109
