### ISSUE TITLE
feat: sebastian - create welcome section 

### ISSUE THREAD

**Issue by blowymind99** [codetapacademy/html-css-javascript-starter#84]
Create welcome section:
* [ ]  feat: sebastian - create the title and subtitle #113
* [ ]  feat: sebastian - Create a section title and a box with shadow #114
* [ ]  feat: sebastian - Create download button #115
* [ ]  feat: sebastian - Create the arrow down #116
