### ISSUE TITLE
feat: vasilemaftita - welcome to the new version

### ISSUE THREAD

**Issue by vasilemaftita** [codetapacademy/html-css-javascript-starter#85]
* [ ] feat: vasilemaftita - title and subtitle created #86
* [ ] feat: vasilemaftita - create a shadow section and a box #89
* [ ] feat: vasilemaftita - creating the download button #90
* [ ] feat: vasilemaftita - continue to create the indicator #91
