### ISSUE TITLE
feat: sebastian - Build connect section 

### ISSUE THREAD

**Issue by blowymind99** [codetapacademy/html-css-javascript-starter#88]
Build connect section: 
* [ ] feat: sebastian - make section title for connect #118
* [ ] feat: sebastian - add image with rounder corners and border #119  
* [ ] feat: sebastian - add list of icons and link to social media #120 
* [ ] feat: sebastian - add continue indicator #121
