### ISSUE TITLE
feat: vasilemaftita - implement connect section

### ISSUE THREAD

**Issue by vasilemaftita** [codetapacademy/html-css-javascript-starter#92]
* [ ] feat: vasilemaftita - to connect, create the section title #93
* [ ] feat: vasilemaftita - add corners and round edges to an image #95
* [ ] feat: vasilemaftita - connect to social media and add a list #104
* [ ] feat: vasilemaftita - then add the indicator #106
