### ISSUE TITLE
feat: sebastian - add skills section 

### ISSUE THREAD

**Issue by blowymind99** [codetapacademy/html-css-javascript-starter#94]
* [ ] feat: sebastian - Create legend list for skills #123
* [ ] feat: sebastian - Add title and skill list #126 
* [ ] feat: sebastian - Create finish content indicator #128
