### ISSUE TITLE
feat: simonamarcu2 - implement connect layout

### ISSUE THREAD

**Issue by simonamarcu2** [codetapacademy/html-css-javascript-starter#96]
* [ ] create category heading for connect #105 
* [ ] insert an image with round corners and border #107
* [ ] insert links and buttons for social media #108
* [ ] insert next button #109
